---
title: "Size effects on toxicity"
author: "Scott Coffin"
date: "5/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Are Mammlian tox thresholds correlated with particle size?

```{r}
# Load packages
library(tidyverse) #General everything
library(ggiraphExtra) #For plotting

human <- read_csv("Humans_Clean_Final.csv", guess_max = 10000) %>% 
  mutate(bio_h_f = factor(case_when(bio.org == "cell"~"Cell", #Renames for widget
                                    bio.org == "organism"~"Organism",
                                    bio.org == "subcell"~"Subcell",
                                    bio.org == "tissue" ~ "Tissue")))%>%
  mutate(vivo_h_f = factor(case_when(invitro.invivo == "invivo"~"In Vivo",
                                     invitro.invivo == "invitro"~"In Vitro")))%>% ##Renames for widget 
  mutate(life_h_f = factor(case_when(life.stage == "early,f1"~"Early, F1 Generation",
                                     life.stage == "early,f2"~"Early, F2 Generation",
                                     life.stage == "adult"~"Adult",
                                     life.stage == "Not Reported"~"Not Reported")))%>% #Renames for widget
  mutate(exposure_route_h_f = factor(case_when(exposure.route == "drinking.water" ~ "Drinking Water",
                                               exposure.route == "food" ~ "Food",
                                               exposure.route == "gavage" ~ "Gavage",
                                               exposure.route == "gestation" ~ "Gestation",
                                               exposure.route == "gestation,lactation" ~ "Gestation & Lactation",
                                               exposure.route ==  "Not Applicable"~"Not Applicable (in vitro)")))%>% #Renames for widget - only categories included under 
                                                                                                                      #ingestion and in vitro are included (we don't want other 
                                                                                                                      #routes of exposure plotted in exploration because there is so little data)
  mutate(species_h_f = factor(case_when(species == "aries"~"(Sheep) Ovis aries",
                                        species == "sapiens"~"(Human) Homo sapiens",
                                        species == "musculus"~"(Mouse) Mus musculus",
                                        species == "cuniculus"~"(Rabbit) Oryctolagus cuniculus",
                                        species == "domesticus" ~ "(Pig) Sus domesticus",
                                        species == "norvegicus"~"(Rat) Rattus norvegicus"))) %>% 
  mutate(effect_10 = case_when(effect == "Y" ~ 1,
                               effect == "N" ~ 0))

```

```{r}
human %>%
  ggplot(aes(x = size.length.um.used.for.conversion, y = dose.mg.mL.master, color = effect)) +
  geom_point() +
  scale_y_log10()
```
Hard to see with a general figure, so let's run a GLM

```{r}
mg.model <- glm(formula = effect_10 ~ dose.mg.mL.master * size.length.um.used.for.conversion,
                family = "binomial", data = human, na.action = "na.exclude")
summary(mg.model)
```
```{r}
ggPredict(mg.model,colorn=800,jitter=FALSE, interactive = FALSE)
```

